import { describe, it, expect } from 'vitest';
import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import path from 'node:path';
import { legacyApiSchema } from '../../lib/legacy-api/yup-validation.js';
import { BALTIC_SEA_BBOX, GEO_LIMITS } from '../../lib/utils/geo/checkBalticSea.js';
// Reines JavaScript ohne Typdeklarationen — dieselbe Import-Situation wie in
// legacy-inbox.contract.test.ts, die betroffenen Dateien tragen `@ts-nocheck`.
import { BBOX, GRENZEN } from '../../../legacy-inbox/src/geo/checkBalticSea.js';
import { legacySchema } from '../../../legacy-inbox/src/validate.js';

/**
 * `legacy-inbox/` is a standalone Node service deployed on its own host. It
 * cannot import from this repository at runtime, so it carries copies of the
 * Baltic Sea geometry and of the legacy validation. The copies are deliberate;
 * their silent divergence is not.
 *
 * These tests are the only thing that notices when a change to a source here
 * is not carried over there. They are deliberately cheap so they can run in
 * `npm run test:quick` on every change.
 *
 * Same idea as `src/routes/rest_sichtungen/antworten.json/frozen.test.ts`,
 * which keeps the frozen answer tables in `legacy-inbox/data/` honest.
 */

const REPO_ROOT = process.cwd();

function sha256(relativePath: string): string {
	return createHash('sha256')
		.update(readFileSync(path.resolve(REPO_ROOT, relativePath)))
		.digest('hex');
}

describe('legacy-inbox stays in sync — spatial index', () => {
	const SOURCE = 'src/lib/server/geo/rbush-index.json';
	const COPY = 'legacy-inbox/src/geo/rbush-index.json';

	it('ships a byte-identical copy of the pre-built RBush index', () => {
		// Hashes, not a deep-equal: the file is several megabytes of geometry
		// and parsing it twice per test run would cost more than it is worth.
		expect(
			sha256(COPY),
			`${COPY} no longer matches ${SOURCE}. The inbox would then answer ` +
				'inBaltic.json from a different Baltic Sea geometry than this application. ' +
				`Re-sync with:\n  cp ${SOURCE} ${COPY}\n` +
				'(The source itself is generated by `npm run geo:build` — regenerate there, ' +
				'never edit either copy by hand.)'
		).toBe(sha256(SOURCE));
	});
});

describe('legacy-inbox stays in sync — geo constants', () => {
	const COPY = 'legacy-inbox/src/geo/checkBalticSea.js';
	const SOURCE = 'src/lib/utils/geo/checkBalticSea.ts';

	// The numbers are never restated here: both sides are imported, so this
	// test cannot drift along with the copy it is guarding.
	it('hardcodes the same Baltic Sea bounding box', () => {
		expect(
			BBOX,
			`BBOX in ${COPY} no longer matches BALTIC_SEA_BBOX in ${SOURCE}. The inbox ` +
				'would then report a different `inchartarea` than this application for points ' +
				'near the edge of the chart area. Copy the current values over, including the ' +
				'comment that explains what they are. The source values are derived from ' +
				'`src/lib/server/geo/baltic-extent.json` by `npm run geo:build`.'
		).toEqual({
			minLon: BALTIC_SEA_BBOX.minLongitude,
			maxLon: BALTIC_SEA_BBOX.maxLongitude,
			minLat: BALTIC_SEA_BBOX.minLatitude,
			maxLat: BALTIC_SEA_BBOX.maxLatitude
		});
	});

	it('hardcodes the same global WGS84 limits', () => {
		expect(
			GRENZEN,
			`GRENZEN in ${COPY} no longer matches GEO_LIMITS in ${SOURCE}. The inbox would ` +
				'then accept or reject implausible coordinates differently than this ' +
				'application. Copy the current values over. No command to run.'
		).toEqual({
			minLon: GEO_LIMITS.MIN_LONGITUDE,
			maxLon: GEO_LIMITS.MAX_LONGITUDE,
			minLat: GEO_LIMITS.MIN_LATITUDE,
			maxLat: GEO_LIMITS.MAX_LATITUDE
		});
	});
});

/** One configured Yup test: its name (`required`, `max`, …) and its message. */
interface ConfiguredTest {
	OPTIONS?: { name?: string; message?: unknown };
}

/**
 * Reads the German messages straight out of a Yup schema, so no hand-written
 * table can go stale. Yup keeps every configured test on `schema.tests`; tests
 * whose message is a function are Yup's own defaults and carry no contract.
 */
function messagesByField(fields: Record<string, unknown>): Record<string, Record<string, string>> {
	const byField: Record<string, Record<string, string>> = {};

	for (const [fieldName, fieldSchema] of Object.entries(fields)) {
		const tests = (fieldSchema as { tests?: ConfiguredTest[] }).tests ?? [];
		const messages: Record<string, string> = {};

		for (const test of tests) {
			const options = test.OPTIONS;
			if (!options?.name || typeof options.message !== 'string') continue;
			messages[options.name] = options.message;
		}

		if (Object.keys(messages).length > 0) byField[fieldName] = messages;
	}

	return byField;
}

/** Pulls the `_general` fallback message out of a source file's own text. */
function generalFallbackMessage(relativePath: string): string {
	const source = readFileSync(path.resolve(REPO_ROOT, relativePath), 'utf8');
	const match = source.match(/_general:\s*\[\s*'([^']+)'/);
	if (!match) {
		throw new Error(
			`No \`_general: ['…']\` fallback message found in ${relativePath}. Either the ` +
				'message moved and this test needs to follow it, or the fallback was dropped.'
		);
	}
	return match[1]!;
}

describe('legacy-inbox stays in sync — validation messages', () => {
	const COPY = 'legacy-inbox/src/validate.js';
	const SOURCE = 'src/lib/legacy-api/yup-validation.ts';

	const expected = messagesByField(legacyApiSchema.fields as Record<string, unknown>);
	const actual = messagesByField(
		(legacySchema as { fields: Record<string, unknown> }).fields as Record<string, unknown>
	);

	it('still finds messages to compare at all', () => {
		// Without this, a change to Yup's internals would empty both sides and
		// turn the guard below into a test that can never fail — worse than no
		// guard, because it would still be trusted.
		expect(
			Object.keys(expected).length,
			`No validation messages could be read out of ${SOURCE}. \`schema.tests[].OPTIONS\` ` +
				'is a Yup internal; a Yup upgrade may have moved it. Fix `messagesByField` in ' +
				'this file before believing any green run below.'
		).toBeGreaterThanOrEqual(5);
	});

	it('ports every German validation message character for character', () => {
		expect(
			actual,
			`The messages in ${COPY} no longer match ${SOURCE}. They are part of the legacy ` +
				'API contract that mobile clients see, so they must match exactly — the copy ' +
				'is to be corrected, not this test. Read the current messages out of ' +
				`${SOURCE} and align every one of them, not only the fields named above. ` +
				'No command to run.'
		).toEqual(expected);
	});

	it('ports the fallback message for unknown validation errors', () => {
		expect(
			generalFallbackMessage(COPY),
			`The \`_general\` fallback message in ${COPY} no longer matches ${SOURCE}. It is ` +
				'not part of the schema, so copy it over by hand. No command to run.'
		).toBe(generalFallbackMessage(SOURCE));
	});
});
