import { describe, it, expect } from 'vitest';
import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import path from 'node:path';
import { legacyApiSchema } from '../../lib/legacy-api/yup-validation.js';
import { BALTIC_SEA_BBOX, GEO_LIMITS } from '../../lib/utils/geo/checkBalticSea.js';
// Reines JavaScript ohne Typdeklarationen — dieselbe Import-Situation wie in
// legacy-inbox.contract.test.ts, die betroffenen Dateien tragen `@ts-nocheck`.
import { BBOX, GRENZEN } from '../../../legacy-inbox/src/geo/checkBalticSea.js';
import { legacySchema } from '../../../legacy-inbox/src/validate.js';

/**
 * `legacy-inbox/` is a standalone Node service deployed on its own host. It
 * cannot import from this repository at runtime, so it carries copies of the
 * Baltic Sea geometry and of the legacy validation. The copies are deliberate;
 * their silent divergence is not.
 *
 * These tests are the only thing that notices when a change to a source here
 * is not carried over there. They are deliberately cheap so they can run in
 * `npm run test:quick` on every change.
 *
 * Same idea as `src/routes/rest_sichtungen/antworten.json/frozen.test.ts`,
 * which keeps the frozen answer tables in `legacy-inbox/data/` honest.
 */

const REPO_ROOT = process.cwd();

function sha256(relativePath: string): string {
	return createHash('sha256')
		.update(readFileSync(path.resolve(REPO_ROOT, relativePath)))
		.digest('hex');
}

describe('legacy-inbox stays in sync — spatial index', () => {
	const SOURCE = 'src/lib/server/geo/rbush-index.json';
	const COPY = 'legacy-inbox/src/geo/rbush-index.json';

	it('ships a byte-identical copy of the pre-built RBush index', () => {
		// Hashes, not a deep-equal: the file is several megabytes of geometry
		// and parsing it twice per test run would cost more than it is worth.
		expect(
			sha256(COPY),
			`${COPY} no longer matches ${SOURCE}. The inbox would then answer ` +
				'inBaltic.json from a different Baltic Sea geometry than this application. ' +
				`Re-sync with:\n  cp ${SOURCE} ${COPY}\n` +
				'(The source itself is generated by `npm run geo:build` — regenerate there, ' +
				'never edit either copy by hand.)'
		).toBe(sha256(SOURCE));
	});
});

describe('legacy-inbox stays in sync — geo constants', () => {
	const COPY = 'legacy-inbox/src/geo/checkBalticSea.js';
	const SOURCE = 'src/lib/utils/geo/checkBalticSea.ts';

	// The numbers are never restated here: both sides are imported, so this
	// test cannot drift along with the copy it is guarding.
	it('hardcodes the same Baltic Sea bounding box', () => {
		expect(
			BBOX,
			`BBOX in ${COPY} no longer matches BALTIC_SEA_BBOX in ${SOURCE}. The inbox ` +
				'would then report a different `inchartarea` than this application for points ' +
				'near the edge of the chart area. Copy the current values over, including the ' +
				'comment that explains what they are. The source values are derived from ' +
				'`src/lib/server/geo/baltic-extent.json` by `npm run geo:build`.'
		).toEqual({
			minLon: BALTIC_SEA_BBOX.minLongitude,
			maxLon: BALTIC_SEA_BBOX.maxLongitude,
			minLat: BALTIC_SEA_BBOX.minLatitude,
			maxLat: BALTIC_SEA_BBOX.maxLatitude
		});
	});

	it('hardcodes the same global WGS84 limits', () => {
		expect(
			GRENZEN,
			`GRENZEN in ${COPY} no longer matches GEO_LIMITS in ${SOURCE}. The inbox would ` +
				'then accept or reject implausible coordinates differently than this ' +
				'application. Copy the current values over. No command to run.'
		).toEqual({
			minLon: GEO_LIMITS.MIN_LONGITUDE,
			maxLon: GEO_LIMITS.MAX_LONGITUDE,
			minLat: GEO_LIMITS.MIN_LATITUDE,
			maxLat: GEO_LIMITS.MAX_LATITUDE
		});
	});
});

/** One configured Yup test: its name (`required`, `max`, …), message and params. */
interface ConfiguredTest {
	OPTIONS?: { name?: string; message?: unknown; params?: Record<string, unknown> };
}

/**
 * Reads the German messages straight out of a Yup schema, so no hand-written
 * table can go stale. Yup keeps every configured test on `schema.tests`; tests
 * whose message is a function are Yup's own defaults and carry no contract.
 */
function messagesByField(fields: Record<string, unknown>): Record<string, Record<string, string>> {
	const byField: Record<string, Record<string, string>> = {};

	for (const [fieldName, fieldSchema] of Object.entries(fields)) {
		const tests = (fieldSchema as { tests?: ConfiguredTest[] }).tests ?? [];
		const messages: Record<string, string> = {};

		for (const test of tests) {
			const options = test.OPTIONS;
			if (!options?.name || typeof options.message !== 'string') continue;
			messages[options.name] = options.message;
		}

		if (Object.keys(messages).length > 0) byField[fieldName] = messages;
	}

	return byField;
}

/** Total number of (field, test) messages a `messagesByField` result carries. */
function countMessages(byField: Record<string, Record<string, string>>): number {
	return Object.values(byField).reduce(
		(total, messages) => total + Object.keys(messages).length,
		0
	);
}

/**
 * Reads the numeric `min`/`max` arguments out of a Yup schema. Yup keeps them
 * on `OPTIONS.params`; the `matches` and `email` tests carry a `regex` param
 * instead, which does not survive a comparison and is skipped.
 */
function limitsByField(fields: Record<string, unknown>): Record<string, Record<string, number>> {
	const byField: Record<string, Record<string, number>> = {};

	for (const [fieldName, fieldSchema] of Object.entries(fields)) {
		const tests = (fieldSchema as { tests?: ConfiguredTest[] }).tests ?? [];
		const limits: Record<string, number> = {};

		for (const test of tests) {
			const { name, params } = test.OPTIONS ?? {};
			if (!name || !params) continue;
			for (const key of ['min', 'max'] as const) {
				const value = params[key];
				if (typeof value === 'number') limits[`${name}.${key}`] = value;
			}
		}

		if (Object.keys(limits).length > 0) byField[fieldName] = limits;
	}

	return byField;
}

/** Total number of (field, limit) arguments a `limitsByField` result carries. */
function countLimits(byField: Record<string, Record<string, number>>): number {
	return Object.values(byField).reduce((total, limits) => total + Object.keys(limits).length, 0);
}

/** Pulls the `_general` fallback message out of a source file's own text. */
function generalFallbackMessage(relativePath: string): string {
	const source = readFileSync(path.resolve(REPO_ROOT, relativePath), 'utf8');
	const match = source.match(/_general:\s*\[\s*'([^']+)'/);
	if (!match) {
		throw new Error(
			`No \`_general: ['…']\` fallback message found in ${relativePath}. Either the ` +
				'message moved and this test needs to follow it, or the fallback was dropped.'
		);
	}
	return match[1]!;
}

/**
 * Fields the copy is allowed to be missing, each with a reason.
 *
 * `datenschutzEinverstaendnis` is declared in the main schema only. The inbox
 * neither maps nor stores mapped data — it validates and keeps the raw
 * payload, and an undeclared field is neither rejected nor stripped
 * (`stripUnknown` is off, see `legacy-inbox/src/validate.js`). Declaring it
 * there would not change any answer the inbox gives today, so the divergence
 * is tolerated rather than papered over.
 *
 * The list is not a place to silence a failure: anything added here must be
 * harmless for the same demonstrable reason.
 */
const FIELDS_ONLY_IN_SOURCE = ['datenschutzEinverstaendnis'];

/**
 * How many messages and limits `messagesByField`/`limitsByField` currently see
 * in the main schema. Asserted exactly, not as a lower bound: Yup does not
 * expose the `required(...)` message of a **number** field on
 * `schema.tests[].OPTIONS` — for `anzahl_gesamt` only `min` and `integer`
 * appear. A drift in that one message therefore stays green here, and the
 * former `toBeGreaterThanOrEqual(5)` could not have noticed if extraction had
 * quietly shrunk further. Raise these numbers together with the schema.
 */
const EXPECTED_MESSAGE_COUNT = 15;
const EXPECTED_LIMIT_COUNT = 8;

/**
 * What this guard covers — and what it does not.
 *
 * Covered: the German message text of every extractable test, the set of
 * declared field names, and the numeric `min`/`max` arguments.
 *
 * Not covered: the declared type of a field (`yup.number()` vs `yup.string()`),
 * the `transform`/`nullable`/`optional` chain, the `matches` and `email`
 * regexes, and the `required(...)` message of number fields (see
 * `EXPECTED_MESSAGE_COUNT`). A divergence in any of those passes unnoticed.
 */
describe('legacy-inbox stays in sync — validation schema', () => {
	const COPY = 'legacy-inbox/src/validate.js';
	const SOURCE = 'src/lib/legacy-api/yup-validation.ts';

	const sourceFields = legacyApiSchema.fields as Record<string, unknown>;
	const copyFields = (legacySchema as { fields: Record<string, unknown> }).fields;

	const expected = messagesByField(sourceFields);
	const actual = messagesByField(copyFields);

	const expectedLimits = limitsByField(sourceFields);
	const actualLimits = limitsByField(copyFields);

	it('still finds every message it expects to compare', () => {
		// Without this, a change to Yup's internals would empty both sides and
		// turn the guard below into a test that can never fail — worse than no
		// guard, because it would still be trusted. An exact count also catches
		// a *partial* loss, which a lower bound cannot.
		expect(
			countMessages(expected),
			`${countMessages(expected)} validation messages could be read out of ${SOURCE}, ` +
				`expected ${EXPECTED_MESSAGE_COUNT}. \`schema.tests[].OPTIONS\` is a Yup ` +
				'internal; a Yup upgrade may have moved it, in which case `messagesByField` in ' +
				'this file must be fixed before any green run below is believable. If the ' +
				'schema itself gained or lost a message, update EXPECTED_MESSAGE_COUNT.'
		).toBe(EXPECTED_MESSAGE_COUNT);
	});

	it('still finds every limit it expects to compare', () => {
		expect(
			countLimits(expectedLimits),
			`${countLimits(expectedLimits)} min/max arguments could be read out of ${SOURCE}, ` +
				`expected ${EXPECTED_LIMIT_COUNT}. Same reasoning as the message count above: ` +
				'either `limitsByField` stopped working or the schema changed. Fix the former, ' +
				'or update EXPECTED_LIMIT_COUNT for the latter.'
		).toBe(EXPECTED_LIMIT_COUNT);
	});

	it('declares the same fields, apart from the documented exceptions', () => {
		expect(
			Object.keys(copyFields).sort(),
			`The field list in ${COPY} no longer matches ${SOURCE}. A field that only exists ` +
				'here silently accepts anything over there, and one that only exists there is ' +
				'validated by a rule this application does not have. Add the missing field to ' +
				`${COPY}, or — if the divergence is provably harmless — add it to ` +
				'FIELDS_ONLY_IN_SOURCE with the reason. No command to run.'
		).toEqual(
			Object.keys(sourceFields)
				.filter((field) => !FIELDS_ONLY_IN_SOURCE.includes(field))
				.sort()
		);
	});

	it('ports every min/max limit', () => {
		// `email.max(64)` → `.max(100)` in one place only would leave the inbox
		// rejecting submissions this application accepts, or the other way round.
		// The message comparison below cannot see that: the text says "gültige
		// E-Mail-Adresse", not the number.
		expect(
			actualLimits,
			`The min/max limits in ${COPY} no longer match ${SOURCE}. The two would then ` +
				'accept different submissions while showing the same message. Align the ' +
				`numbers in ${COPY}. No command to run.`
		).toEqual(expectedLimits);
	});

	it('ports every German validation message character for character', () => {
		expect(
			actual,
			`The messages in ${COPY} no longer match ${SOURCE}. They are part of the legacy ` +
				'API contract that mobile clients see, so they must match exactly — the copy ' +
				'is to be corrected, not this test. Read the current messages out of ' +
				`${SOURCE} and align every one of them, not only the fields named above. ` +
				'No command to run.'
		).toEqual(expected);
	});

	it('ports the fallback message for unknown validation errors', () => {
		expect(
			generalFallbackMessage(COPY),
			`The \`_general\` fallback message in ${COPY} no longer matches ${SOURCE}. It is ` +
				'not part of the schema, so copy it over by hand. No command to run.'
		).toBe(generalFallbackMessage(SOURCE));
	});
});
