import crypto from 'crypto';

/**
 * Encodes a Buffer to a base64url string.
 * 
 * Base64url encoding is a variant of base64 encoding that replaces URL-unsafe
 * characters with URL-safe alternatives:
 * - '+' becomes '-'
 * - '/' becomes '_'  
 * - '=' padding is removed
 * 
 * This encoding is commonly used in OAuth 2.0 PKCE flows and JWT tokens.
 * 
 * @param buffer - The Buffer to encode
 * @returns A base64url encoded string
 * 
 * @example
 * ```typescript
 * const buffer = Buffer.from('hello world');
 * const encoded = base64URLEncode(buffer);
 * console.log(encoded); // 'aGVsbG8gd29ybGQ'
 * ```
 */
export function base64URLEncode(buffer: Buffer): string {
	return buffer.toString('base64').replace(/\+/g, '-').replace(/\//g, '_').replace(/=/g, '');
}

/**
 * Generates a Proof Key for Code Exchange (PKCE) verifier.
 *
 * This function creates a cryptographically random string that can be used
 * as a PKCE verifier in OAuth 2.0 authorization flows. The verifier is
 * generated using 32 random bytes, which are then base64url encoded.
 * 
 * The PKCE verifier is used client-side and must be kept secret until
 * it's used to exchange the authorization code for tokens.
 *
 * @returns A base64url encoded string to be used as the PKCE verifier
 * 
 * @example
 * ```typescript
 * const verifier = getPKCEVerifier();
 * console.log(verifier); // 'dBjftJeZ4CVP-mB92K27uhbUJU1p1r_wW1gFWFOEjXk'
 * ```
 */
export function getPKCEVerifier(): string {
	return base64URLEncode(crypto.randomBytes(32));
}

/**
 * Creates a SHA-256 hash of the given string.
 * 
 * This function is used internally for PKCE challenge generation,
 * where the verifier is hashed to create the challenge.
 * 
 * @param buffer - The string to hash
 * @returns A Buffer containing the SHA-256 hash
 * 
 * @example
 * ```typescript
 * const hash = sha256('hello world');
 * console.log(hash.toString('hex')); // 'b94d27b9934d3e08a52e52d7da7dabfac484efe37a5380ee9088f7ace2efcde9'
 * ```
 */
export function sha256(buffer: string): Buffer {
	return crypto.createHash('sha256').update(buffer).digest();
}

/**
 * Generates PKCE challenge data for OAuth 2.0 authorization flows.
 *
 * This function creates both the PKCE verifier and its corresponding challenge.
 * The challenge is generated by taking the SHA-256 hash of the verifier and
 * base64url encoding it. This implements the S256 challenge method as specified
 * in RFC 7636.
 * 
 * The verifier should be stored securely on the client side and used later
 * to exchange the authorization code for tokens. The challenge is sent to
 * the authorization server as part of the authorization request.
 *
 * @returns An object containing both the verifier and challenge strings
 * 
 * @example
 * ```typescript
 * const { verifier, challenge } = getPKCEChallengeData();
 * console.log('Verifier:', verifier);
 * console.log('Challenge:', challenge);
 * // Store verifier securely, send challenge to auth server
 * ```
 */
export function getPKCEChallengeData() {
	const verifier = getPKCEVerifier();
	const challenge = base64URLEncode(sha256(verifier));
	return { verifier, challenge };
}

/**
 * The AES-256-GCM algorithm identifier used for encryption/decryption.
 * 
 * GCM (Galois/Counter Mode) provides both confidentiality and authenticity,
 * making it ideal for securing sensitive data like PKCE verifiers.
 */
const ALGORITHM = 'aes-256-gcm';

/**
 * Encrypts text using AES-256-GCM encryption.
 * 
 * This function provides authenticated encryption, ensuring both confidentiality
 * and integrity of the encrypted data. It generates a random initialization vector (IV)
 * for each encryption operation and returns the IV, encrypted data, and authentication
 * tag separately.
 * 
 * AES-256-GCM is chosen for its security properties:
 * - AES-256 provides strong encryption with a 256-bit key
 * - GCM mode provides authenticated encryption
 * - Random IV ensures each encryption is unique
 * 
 * @param text - The plaintext string to encrypt
 * @param key - A 32-byte Buffer containing the encryption key
 * @returns An object containing the IV, encrypted data, and authentication tag as Buffers
 * 
 * @example
 * ```typescript
 * const key = crypto.randomBytes(32);
 * const result = encrypt('sensitive data', key);
 * console.log('IV:', result.iv.toString('hex'));
 * console.log('Encrypted:', result.encryptedData.toString('hex'));
 * console.log('Tag:', result.tag.toString('hex'));
 * ```
 * 
 * @throws Will throw an error if the key is not 32 bytes long
 */
export const encrypt = (text: string, key: Buffer): { iv: Buffer; encryptedData: Buffer; tag: Buffer } => {
	const iv = crypto.randomBytes(16);
	const cipher = crypto.createCipheriv(ALGORITHM, key, iv);
	const encryptedData = Buffer.concat([cipher.update(text, 'utf8'), cipher.final()]);
	const tag = cipher.getAuthTag();
	return { iv, encryptedData, tag };
};

/**
 * Decrypts data that was encrypted using the encrypt function.
 * 
 * This function performs authenticated decryption using AES-256-GCM. It verifies
 * the authentication tag to ensure the data has not been tampered with before
 * decrypting. If the tag verification fails, the function will throw an error.
 * 
 * @param encryptedData - The encrypted data as a Buffer
 * @param key - The same 32-byte Buffer that was used for encryption
 * @param iv - The initialization vector that was used for encryption
 * @param tag - The authentication tag from the encryption operation
 * @returns The decrypted plaintext as a string
 * 
 * @example
 * ```typescript
 * const key = crypto.randomBytes(32);
 * const { iv, encryptedData, tag } = encrypt('sensitive data', key);
 * const decrypted = decrypt(encryptedData, key, iv, tag);
 * console.log(decrypted); // 'sensitive data'
 * ```
 * 
 * @throws Will throw an error if authentication fails or if the key/IV are incorrect
 */
export const decrypt = (encryptedData: Buffer, key: Buffer, iv: Buffer, tag: Buffer): string => {
	const decipher = crypto.createDecipheriv(ALGORITHM, key, iv);
	decipher.setAuthTag(tag);
	const decryptedData = Buffer.concat([decipher.update(encryptedData), decipher.final()]);
	return decryptedData.toString('utf8');
};